services:
  jekyll:
    build:
      context: .
      args:
        - USER=${USER}
        - BLOG_URL=${BLOG_URL}
        - GIT_TOKEN=${GIT_TOKEN}
    ports:
      - "4000:4000"
    # volumes:
    #   - .:/srv/jekyll
    #   - ./vendor/bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    entrypoint: ["sh", "-c", "./start.sh"]
    # entrypoint: ["sh", "-c", "sleep infinity"]